{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Order' %}{% endblock %}

{% set periods = guest.system_periods %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% trans 'Select Product' %}
                    <small>{% trans 'Choose products we offer for selling' %}</small>
                </h1>
				{% include "partial_steps.phtml" with {'selected': 1} %}
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}

		<div class="row">
			<div class="col-md-12">
							
					<!-- Tab panes -->
					<div class="tab-content">
						{% for i, category in guest.product_category_get_list.list %}
							<div role="tabpanel" class="tab-pane active" id="collapse-cat{{category.id}}">
								{% set listing_template = 'mod_service'~category.type~'_listing.phtml' %}
								{% if guest.system_template_exists({"file":listing_template}) %}
								<div class="mod_service{{category.type}} panel-body">{% include listing_template %}</div>
								{% else %}
								{% for product in category.products %}
								<div class="product_frame">
									<div class="row">
										<div class="col-md-8">
											<h4 class="list-group-item-heading order_title">{{ product.title }}</h4>

											<div class="list-group-item-text">
												{% if product.icon_url %}
												<div class="pull-left">
													{{ product.icon_url | img_tag }}
												</div>
												{% endif %}
												{{ product.description|bbmd }}
											</div>

										</div>
										<div class="col-md-4" align="center">
											<p>{% if product.pricing.type == 'recurrent' %}
												<strong>{% trans 'Starting from' %}</strong>
												<br/> 
												<select name="period" id="period-selector" class="form-control starting_price">
													{% for code,prices in product.pricing.recurrent %}
													{% if prices.enabled %}<option value="{{code}}">{{ prices.price | money_convert }} {{ periods[code] }}</option>{% endif %}
													{% endfor %}
												</select>	
												{% else %}
												<strong>{% trans 'Starting from' %}</strong>
												<br/> 
												<strong class="starting_price">{{ product.price_starting_from | money_convert }}</strong>
												{% endif %}
											</p>
											<div align="center">
												<a class="btn btn-primary btn-order" href="{{ '/order'|link }}/{{ product.slug }}"><i class="fa fa-shopping-cart"></i>&nbsp;&nbsp;{% trans 'Order now' %}</a>
											</div>											
										</div>
									</div>
								</div>
								{% endfor %}
								{% endif %}		
							</div>
						{% endfor %}
					</div>
				
			</div>
		</div>

        <script>
        	jQuery(document).ready(function($) {
        		$('#sidebar3').prepend(`

        			<div class="panel panel-default">
        			  <div class="panel-heading"><i class="fa fa-shopping-cart"></i>&nbsp;&nbsp;Categories </div>
        			  <div class="panel-body categories">
							{% for i, category in guest.product_category_get_list.list %}
								<a href="#collapse-cat{{category.id}}" aria-controls="collapse-cat{{category.id}}" role="tab" data-toggle="tab">{{ category.title }}</a>
							{% endfor %}
        			  </div>
        			</div>
        			`)		

        		$('.product-category').eq(0).click();

        		$('#accordion .panel').each(function(index, el) {
        			count = $(this).find('.list-group-item').length;
        			$(this).find('.list-group-item').addClass('col-md-' + (12 / count) ) ;

        		});

        	});
        </script>
		
{% endblock %}

{% block sidebar %}
	<div class="well">
		{% include 'partial_currency.phtml' %}
	</div>
{% endblock %}

