{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Order' %}{% endblock %}

{% set periods = guest.system_periods %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% trans 'Select Product' %}
                    <small>{% trans 'Choose products we offer for selling' %}</small>
                </h1>
				{% include "partial_steps.phtml" with {'selected': 1} %}
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}

        <!-- Content Row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel-group" id="accordion">
				{% for i, category in guest.product_category_get_list.list %}
					<div class="panel panel-default" style="border:none;">
                        <div id="collapse-cat{{category.id}}" class="panel-collapse collapse">
							{% set listing_template = 'mod_service'~category.type~'_listing.phtml' %}
							{% if guest.system_template_exists({"file":listing_template}) %}
							<div class="mod_service{{category.type}} panel-body">{% include listing_template %}</div>
							{% else %}
							{% for product in category.products %}
							<div class="list-group-item category-group-item">
								<h4 class="list-group-item-heading">{{ product.title }}</h4>

								<div class="list-group-item-text">
									{% if product.icon_url %}
									<div class="pull-left">
										{{ product.icon_url | img_tag }}
									</div>
									{% endif %}
									{{ product.description|bbmd }}
								</div>

								<p>{% if product.pricing.type == 'recurrent' %}
									{% trans 'Starting from' %} 
									<select name="period" id="period-selector" class="form-control">
										{% for code,prices in product.pricing.recurrent %}
										{% if prices.enabled %}<option value="{{code}}">{{ prices.price | money_convert }} {{ periods[code] }}</option>{% endif %}
										{% endfor %}
									</select>	
									{% else %}
									{% trans 'Starting from' %} <strong>{{ product.price_starting_from | money_convert }}</strong>
									{% endif %}
								</p>
								<div align="center">
									<a class="btn btn-success" href="{{ '/order'|link }}/{{ product.slug }}"><i class="fa fa-shopping-cart"></i> {% trans 'Order now' %}</a>
								</div>
							</div>
							{% endfor %}
							{% endif %}		
							

                        </div>
                    </div>
                    <!-- /.panel -->
					
				{% endfor %}

                </div>
                <!-- /.panel-group -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <script>
        	jQuery(document).ready(function($) {
        		$('#sidebar3').prepend(`
        			<div class="panel panel-default">
        			  <div class="panel-heading"><i class="fa fa-shopping-cart"></i>&nbsp;&nbsp;Categories </div>
        			  <div class="panel-body categories">
        			  	{% for i, category in guest.product_category_get_list.list %}
        			  		<a class="product-category" data-toggle="collapse" data-parent="#accordion" href="#collapse-cat{{category.id}}">{{ category.title }}</a>
        			  	{% endfor %}
        			  </div>
        			</div>
        			`)		

        		$('.product-category').eq(0).click();

        		$('#accordion .panel').each(function(index, el) {
        			count = $(this).find('.list-group-item').length;
        			$(this).find('.list-group-item').addClass('col-md-' + (12 / count) ) ;

        		});

        	});
        </script>
		
{% endblock %}

{% block sidebar %}
	<div class="well">
		{% include 'partial_currency.phtml' %}
	</div>
{% endblock %}

