{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'My Products & Services' %}{% endblock %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">My Product & Services</h1>
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}

        <table>
            <thead>
                <tr>
                    <th>Product / Services</th>
                    <th>Pricing</th>
                    <th>Next Due Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% set orders = client.order_get_list({"hide_addons":1}) %}
                {% for i, order in orders.list %}
                <tr>
                    <td><a href="{{ '/order/service/manage'|link }}/{{order.id}}">{{order.title}}</a></td>
                    <td>{{  order.total | money(order.currency) }} {% if order.period%}<span class="order_period">{{ order.period | period_title }}</span>{% endif %}</td>
                    <td>{{order.expires_at|date('d-m-Y')}}</td>
                    <td><span class="pull-right label {% if order.status == "active" %}label-success{% elseif order.status == "pending_setup" %}label-warning{% elseif order.status == "failed_setup" %}label-danger{% else %}label-default{% endif %}">{{ mf.status_name(order.status) }}</span></td>
                </tr>
                {% else %}{% trans 'The list is empty' %}
                {% endfor %}
            </tbody>
        </table>

{% endblock %}